### ISSUE TITLE
Crash when trying to run at detached HEAD state

### ISSUE THREAD

**Issue by plloppii** [re3Dprinting/touchscreen#82]
If checking out an old commit, the software crashes and gives the following error:

Traceback (most recent call last):
  File "/Users/npan/re3d/touchscreen/ClientApp/util/load_properties.py", line 44, in get_properties
    properties["version"] = current_version.name
AttributeError: 'NoneType' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/touchscreen/main.py", line 231, in <module>
    MainHandler()
  File "src/touchscreen/main.py", line 83, in __init__
    properties = get_properties(self.persona, "developer")
  File "/Users/npan/re3d/touchscreen/ClientApp/util/load_properties.py", line 47, in get_properties
    properties["version"] = repo.active_branch.name
  File "/Users/npan/re3d/OctoPrint/venv/lib/python3.7/site-packages/git/repo/base.py", line 703, in active_branch
    return self.head.reference
  File "/Users/npan/re3d/OctoPrint/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 272, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'edf17d70a6660c23cef418c6063c3588648e571c'

**Comment by plloppii** [comment]
Have not seen this issue since devel/1.0.28
